/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author viict
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1QtRestricoes = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jLabel2Restricoes = new javax.swing.JLabel();
        jLabel3Variaveis = new javax.swing.JLabel();
        jSpinner2QtVariaveis = new javax.swing.JSpinner();
        jLabelFundoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSpinner1QtRestricoes);
        jSpinner1QtRestricoes.setBounds(200, 170, 100, 30);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Simplex - BigM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 180, 50);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(170, 240, 130, 40);

        jLabel2Restricoes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2Restricoes.setText("Quantas restrições ?");
        getContentPane().add(jLabel2Restricoes);
        jLabel2Restricoes.setBounds(30, 150, 190, 70);

        jLabel3Variaveis.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3Variaveis.setText("Quantas variáveis ?");
        getContentPane().add(jLabel3Variaveis);
        jLabel3Variaveis.setBounds(30, 80, 190, 70);
        getContentPane().add(jSpinner2QtVariaveis);
        jSpinner2QtVariaveis.setBounds(200, 100, 100, 30);

        jLabelFundoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.jpg"))); // NOI18N
        jLabelFundoInicio.setText("Simplex - BigM");
        getContentPane().add(jLabelFundoInicio);
        jLabelFundoInicio.setBounds(-10, -10, 640, 430);

        setSize(new java.awt.Dimension(624, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Restricoes;
    private javax.swing.JLabel jLabel3Variaveis;
    private javax.swing.JLabel jLabelFundoInicio;
    private javax.swing.JSpinner jSpinner1QtRestricoes;
    private javax.swing.JSpinner jSpinner2QtVariaveis;
    // End of variables declaration//GEN-END:variables
}
