/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author viict
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1PlanoDeFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2Ferramentas = new javax.swing.JMenu();
        jMenuItem1TelaInicial = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();
        jMenuItem1SAIR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1PlanoDeFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1PlanoDeFundoTelaPrincipal);
        jLabel1PlanoDeFundoTelaPrincipal.setBounds(0, -20, 630, 460);

        jMenu2Ferramentas.setText("Ferramentas");

        jMenuItem1TelaInicial.setText("Tela-Inicial");
        jMenuItem1TelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1TelaInicialActionPerformed(evt);
            }
        });
        jMenu2Ferramentas.add(jMenuItem1TelaInicial);

        jMenuBar1.add(jMenu2Ferramentas);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3SairActionPerformed(evt);
            }
        });

        jMenuItem1SAIR.setText("SAIR");
        jMenuItem1SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1SAIRActionPerformed(evt);
            }
        });
        jMenu3Sair.add(jMenuItem1SAIR);

        jMenuBar1.add(jMenu3Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(634, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1TelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1TelaInicialActionPerformed
        Inicio tela = new Inicio();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1TelaInicialActionPerformed

    private void jMenu3SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairActionPerformed

    private void jMenuItem1SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SAIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1SAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1PlanoDeFundoTelaPrincipal;
    private javax.swing.JMenu jMenu2Ferramentas;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1SAIR;
    private javax.swing.JMenuItem jMenuItem1TelaInicial;
    // End of variables declaration//GEN-END:variables
}
